version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.14.0-alpine
    restart: on-failure
    ports:
      - "${PORTAINER_PORT}:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nextcloud:
    image: nextcloud:24.0.2-fpm
    restart: on-failure
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD

  postgres:
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./images/postgres/multiple-databases:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES

volumes:
  portainer_data:
  nextcloud:
  postgres:
